// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXExwqe6cK9MKMJmaGhk9qgI5QB76yUAw',
    appId: '1:741293531855:web:fc407aa6c93f4d50408dba',
    messagingSenderId: '741293531855',
    projectId: 'mdigits-span-tasks-ema',
    authDomain: 'mdigits-span-tasks-ema.firebaseapp.com',
    storageBucket: 'mdigits-span-tasks-ema.appspot.com',
    measurementId: 'G-W448FPETS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM87zBTQoAbuN95ifrgno8o4BWz6nCXU8',
    appId: '1:741293531855:android:9d4ead93f1b36202408dba',
    messagingSenderId: '741293531855',
    projectId: 'mdigits-span-tasks-ema',
    storageBucket: 'mdigits-span-tasks-ema.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlmMWhhjkHPsaHzh1zVKzGhF1FgeoS-Mc',
    appId: '1:741293531855:ios:c73ce9eb30b747fa408dba',
    messagingSenderId: '741293531855',
    projectId: 'mdigits-span-tasks-ema',
    storageBucket: 'mdigits-span-tasks-ema.appspot.com',
    iosBundleId: 'com.example.mdigitSpanTasks',
  );
}
